const ICONS: Record<string, string> = {
  React: 'https://skillicons.dev/icons?i=react',
  TypeScript: 'https://skillicons.dev/icons?i=ts',
  'Vue.js': 'https://skillicons.dev/icons?i=vue',
  'Tailwind CSS': 'https://skillicons.dev/icons?i=tailwind',
  'Framer Motion': 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/framer.svg',
  Vite: 'https://skillicons.dev/icons?i=vite',
  HTML5: 'https://skillicons.dev/icons?i=html',
  CSS3: 'https://skillicons.dev/icons?i=css',
  NestJS: 'https://skillicons.dev/icons?i=nestjs',
  'Node.js': 'https://skillicons.dev/icons?i=nodejs',
  Laravel: 'https://skillicons.dev/icons?i=laravel',
  PHP: 'https://skillicons.dev/icons?i=php',
  Python: 'https://skillicons.dev/icons?i=python',
  GraphQL: 'https://skillicons.dev/icons?i=graphql',
  'REST APIs': 'https://skillicons.dev/icons?i=postman',
  AWS: 'https://skillicons.dev/icons?i=aws',
  Terraform: 'https://skillicons.dev/icons?i=terraform',
  Docker: 'https://skillicons.dev/icons?i=docker',
  'CI/CD': 'https://skillicons.dev/icons?i=githubactions',
  ECS: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazonecs.svg',
  RDS: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazonrds.svg',
  S3: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazons3.svg',
  CloudFront: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazoncloudfront.svg',
  SQLite: 'https://skillicons.dev/icons?i=sqlite',
  Prisma: 'https://skillicons.dev/icons?i=prisma',
  Redis: 'https://skillicons.dev/icons?i=redis',
  MySQL: 'https://skillicons.dev/icons?i=mysql',
  DynamoDB: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazondynamodb.svg',
  JWT: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/jsonwebtokens.svg',
  OAuth2: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/oauth.svg',
  'Event-driven architecture': 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/apachekafka.svg',
  CQRS: 'https://skillicons.dev/icons?i=redux',
  'Domain-driven design (DDD)': 'https://skillicons.dev/icons?i=devto',
  'Design patterns': 'https://skillicons.dev/icons?i=devto',
  Lambda: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/awslambda.svg',
  CloudWatch: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazoncloudwatch.svg',
  Route53: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazonroute53.svg',
  IAM: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazoniam.svg',
  Cognito: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazoncognito.svg',
  CodePipeline: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazoncodepipeline.svg',
  ECR: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazonelasticcontainerregistry.svg',
  SQS: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazonsqs.svg',
  SNS: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazonsns.svg',
  Kubernetes: 'https://skillicons.dev/icons?i=kubernetes',
  'Docker Compose': 'https://skillicons.dev/icons?i=docker',
  'Nginx reverse proxy hardening': 'https://skillicons.dev/icons?i=nginx',
  'OWASP Top 10': 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/owasp.svg',
  'Secure SDLC': 'https://skillicons.dev/icons?i=git',
  'Threat modeling': 'https://skillicons.dev/icons?i=devto',
  'Secrets management': 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/hashicorp.svg',
  'SAST/DAST': 'https://skillicons.dev/icons?i=githubactions',
  'Structured logging': 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/elasticstack.svg',
  'Metrics/alerting': 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/prometheus.svg',
  OpenTelemetry: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/opentelemetry.svg',
  'Grafana stack': 'https://skillicons.dev/icons?i=grafana',
  'Web Vitals': 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/lighthouse.svg',
  'Bundle optimization': 'https://skillicons.dev/icons?i=vite',
  'Caching/CDN strategy': 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/cloudflare.svg',
  'DB indexing/query tuning': 'https://skillicons.dev/icons?i=mysql',
  PostgreSQL: 'https://skillicons.dev/icons?i=postgres',
  'Redis patterns': 'https://skillicons.dev/icons?i=redis',
  'Data modeling': 'https://skillicons.dev/icons?i=postgres',
};

export function getSkillIcon(name: string): string {
  return ICONS[name] ?? 'https://skillicons.dev/icons?i=devto';
}
